### ISSUE TITLE
Player City NPE

### ISSUE THREAD

**Issue by WizardCM** [chaseoes/FirstJoinPlus#29]
I sometimes have players that don't get teleported on first join. I have a feeling this NPE is connected to the issue, though I find it unlikely. I do not have `%player_city` in use on my join message, but I do have `%player_country`.

    [23:25:03 ERROR]: Could not pass event FirstJoinEvent to FirstJoinPlus v2.2
    org.bukkit.event.EventException
            at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[spigot.jar:git-Spigot-1589]
            at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1589]
            at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1589]
            at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1589]
            at com.chaseoes.firstjoinplus.PlayerListeners.firstJoinDetection(PlayerListeners.java:31) [FirstJoinPlus.jar:?]
            at sun.reflect.GeneratedMethodAccessor373.invoke(Unknown Source) ~[?:?]
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
            at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_21]
            at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) [spigot.jar:git-Spigot-1589]
            at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-1589]
            at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1589]
            at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1589]
            at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:265) [spigot.jar:git-Spigot-1589]
            at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:152) [spigot.jar:git-Spigot-1589]
            at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:105) [spigot.jar:git-Spigot-1589]
            at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:43) [spigot.jar:git-Spigot-1589]
            at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:187) [spigot.jar:git-Spigot-1589]
            at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1589]
            at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1589]
            at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1589]
            at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1589]
            at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1589]
            at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1589]
    Caused by: java.lang.NullPointerException
            at java.lang.String.replace(Unknown Source) ~[?:1.7.0_21]
            at com.chaseoes.firstjoinplus.utilities.Utilities.replaceVariables(Utilities.java:159) ~[?:?]
            at com.chaseoes.firstjoinplus.FirstJoinListener.onFirstJoin(FirstJoinListener.java:25) ~[?:?]
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_21]
            at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_21]
            at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_21]
            at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[spigot.jar:git-Spigot-1589]
            ... 22 more

**Comment by WizardCM** [comment]
Just wanted to mention that this still occasionally happens.

**Comment by chaseoes** [comment]
Is this still an issue?

**Comment by WizardCM** [comment]
I can't say I've seen it in a while, no. Which is a good thing. xD
