### ISSUE TITLE
FJP 1.7.9 error

### ISSUE THREAD

**Issue by hamhamfreak** [chaseoes/FirstJoinPlus#38]
[18:25:31] [Server thread/WARN]: [FirstJoinPlus] Task #74 for FirstJoinPlus v2.2 generated an exception
java.lang.NullPointerException
at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[spigot-1.7.10.jar:git-Spigot-1627]
at com.chaseoes.firstjoinplus.utilities.Utilities.getFirstJoinKit(Utilities.java:76) ~[?:?]
at com.chaseoes.firstjoinplus.FirstJoinListener$1.run(FirstJoinListener.java:35) ~[?:?]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.7.10.jar:git-Spigot-1627]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.7.10.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot-1.7.10.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10.jar:git-Spigot-1627]
[18:25:32] [User Authenticator #2/INFO]: UUID of player _MiAmI_ is 56e5c781-206a-4eb4-9aee-a2895eb0fad2
[18:25:32] [Server thread/INFO]: _MiAmI_[/99.49.193.216:60380] logged in with entity id 3 at ([hub] -68.35637038338896, 73.0, -889.1226167418263)
[18:25:32] [Server thread/WARN]: [FirstJoinPlus] Task #89 for FirstJoinPlus v2.2 generated an exception
java.lang.NullPointerException
at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[spigot-1.7.10.jar:git-Spigot-1627]
at com.chaseoes.firstjoinplus.utilities.Utilities.getFirstJoinKit(Utilities.java:76) ~[?:?]
at com.chaseoes.firstjoinplus.FirstJoinListener$1.run(FirstJoinListener.java:35) ~[?:?]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.7.10.jar:git-Spigot-1627]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.7.10.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot-1.7.10.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10.jar:git-Spigot-1627]

**Comment by chaseoes** [comment]
Sounds like you're using a bad item name in your configuration.
