### ISSUE TITLE
Spigot 1.9 problem

### ISSUE THREAD

**Issue by maxlehot1234** [chaseoes/FirstJoinPlus#41]
Hi, I get this when I login on my test server using Spigot 1.9 and FJP 2.2...

http://pastebin.com/jcu87Yrm

Any way to update it to 1.9 ?

Thank you

**Comment by tmad40blue** [comment]
@maxlehot1234 @chaseoes 

Confirmed - this is related to getOnlinePlayers() being a deprecated method in Spigot 1.9.

Stacktrace:

```
[09:35:43] [Craft Scheduler Thread - 9/WARN]: Exception in thread "Craft Scheduler Thread - 9"                                                                                                                                                                                                                                
[09:35:43] [Craft Scheduler Thread - 9/WARN]: org.apache.commons.lang.UnhandledException: Plugin FirstJoinPlus v2.2 generated an exception while executing task 56                                                                                                                                                            
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)                                                                                                                                                                                                                                
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                                                                                                                                                                                                                                    
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                                                                                                                                                                                                                                    
        at java.lang.Thread.run(Thread.java:745)                                                                                                                                                                                                                                                                              
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;                                                                                                                                                                                                                       
        at org.mcstats.Metrics.postPlugin(Metrics.java:335)                                                                                                                                                                                                                                                                   
        at org.mcstats.Metrics.access$400(Metrics.java:57)                                                                                                                                                                                                                                                                    
        at org.mcstats.Metrics$1.run(Metrics.java:223)                                                                                                                                                                                                                                                                        
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)                                                                                                                                                                                                                                          
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)                                                                                                                                                                                                                                
        ... 3 more                                                                                                                                                                                                                                                                                                            
             
```

May be possible to temporarily fix with the method outlined [here](https://www.spigotmc.org/threads/minecraft-1-9-release.127186/) related to SpecialSource. Haven't tested it myself.

**Comment by RoboMWM** [comment]
Not just in metrics either:

```log
[03:14:56 ERROR]: Could not pass event PlayerQuitEvent to FirstJoinPlus v2.2                                                            
org.bukkit.event.EventException                                                                                                         
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.9.jar:git-Paper-465]                
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.jar:git-Paper-465]                     
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.jar:git-Paper-465]                  
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.jar:git-Paper-465]                
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.jar:git-Paper-465]                
        at net.minecraft.server.v1_9_R1.PlayerList.disconnect(PlayerList.java:400) [patched_1.9.jar:git-Paper-465]                      
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1054) [patched_1.9.jar:git-Paper-465]                  
        at net.minecraft.server.v1_9_R1.NetworkManager.handleDisconnection(NetworkManager.java:317) [patched_1.9.jar:git-Paper-465]     
        at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:175) [patched_1.9.jar:git-Paper-465]                   
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:876) [patched_1.9.jar:git-Paper-465]                     
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-465]                     
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-465]                     
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-465]                   
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]                                                                           
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;                                 
        at com.chaseoes.firstjoinplus.utilities.Utilities.getRandomPlayer(Utilities.java:151) ~[?:?]                                    
        at com.chaseoes.firstjoinplus.utilities.Utilities.replaceVariables(Utilities.java:161) ~[?:?]                                   
        at com.chaseoes.firstjoinplus.PlayerListeners.onPlayerQuit(PlayerListeners.java:73) ~[?:?]                                      
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]                                                    
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]                                  
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]                          
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]                                                               
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.9.jar:git-Paper-465]                
        ... 13 more
```

**Comment by chaseoes** [comment]
No ETA for the update. Pull requests are welcome.

**Comment by chaseoes** [comment]
Update for 1.9 compatibility completed in 8c876399c6e64a68321454b90e465344c45ab05b.

Download version 2.3 from BukkitDev: http://dev.bukkit.org/bukkit-plugins/firstjoinplus/files/26-first-join-plus-v2-3/
