### ISSUE TITLE
Sound enums need to be updated for Minecraft 1.9

### ISSUE THREAD

**Issue by tmad40blue** [chaseoes/FirstJoinPlus#42]
Sound enum stuff has changed drastically in 1.9 and is causing FJP's first-join sound feature to not work. Stacktrace below:

```
[12:48:28 WARN]: [FirstJoinPlus] Task #527013 for FirstJoinPlus v2.2 generated an exception
java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.LEVEL_UP
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_66]
        at org.bukkit.Sound.valueOf(Sound.java:1) ~[spigot.jar:git-Spigot-1a196e1-6f032cd]
        at com.chaseoes.firstjoinplus.FirstJoinListener$1.run(FirstJoinListener.java:59) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-1a196e1-6f032cd]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-1a196e1-6f032cd]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-1a196e1-6f032cd]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

**Comment by chaseoes** [comment]
No ETA for the update. Pull requests are welcome.

**Comment by chaseoes** [comment]
You can fix this yourself by updating your configuration to the new sound name. 

Change the value of `sound` under `fun-stuff.play-sound` to the following: `ENTITY_PLAYER_LEVELUP`

**Comment by chaseoes** [comment]
Default configuration updated in 8c876399c6e64a68321454b90e465344c45ab05b.
