### ISSUE TITLE
New version still not working.

### ISSUE THREAD

**Issue by ManBeastPig** [chaseoes/FirstJoinPlus#43]
12:33:15
 Vault:
No new version available
12:33:15
 CONSOLE:
ERROR]: Could not pass event FirstJoinEvent to FirstJoinPlus v2.2
12:33:15
 CONSOLE:
Method) ~[?:1.8.0_72]
12:33:15
 CONSOLE:
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
12:33:15
 CONSOLE:
Method) ~[?:1.8.0_72]
12:33:15
 CONSOLE:
MrSulu has logged in.
12:33:15
 CONSOLE:
[INFO] MrSulu[/77.97.153.251:56855] logged in with entity id 273 at ([WandsVsGuns]204.77746945369248, 91.0, 625.6923781977739)
12:33:15
 CONSOLE:
WARN]: MrSulu moved too quickly! -42.27153303188507,-81.0,-1080.9489266474063
12:33:15
 CONSOLE:
[INFO] Resource pack hash set to 73ffad81a98a67e584df70c2d8ac93cf, Padding resource pack hash to 40 chars
12:33:15
 Magic:
Essentials found, hooked up custom item handler

**Comment by chaseoes** [comment]
`Could not pass event FirstJoinEvent to FirstJoinPlus v2.2`

You're not using the right version. You might be auto-updating to the older version until it's approved on BukkitDev.

Should be on v2.3, downloaded from here: http://dev.bukkit.org/bukkit-plugins/firstjoinplus/files/26-first-join-plus-v2-3/

**Comment by ManBeastPig** [comment]
OK i'll disable auto update and try again.

**Comment by ManBeastPig** [comment]
12:49:46
 CONSOLE:
[INFO] MrSulu[/77.97.153.251:38049] logged in with entity id 314 at ([WandsVsGuns]210.5, 91.0, 616.5)
12:49:46
 CONSOLE:
WARN]: [FirstJoinPlus] Task #111 for FirstJoinPlus v2.3 generated an exception

Its giving the welcome message but not processing the kits or xp etc etc.

**Comment by chaseoes** [comment]
There should be more to the error message than that. Find it and upload it to Pastebin?

**Comment by ManBeastPig** [comment]
http://pastebin.com/D5iW5vhJ

**Comment by chaseoes** [comment]
Looks like a bad version somehow got uploaded. Download it again from here:

http://dev.bukkit.org/bukkit-plugins/firstjoinplus/files/27-first-join-plus-v2-3/

**Comment by ManBeastPig** [comment]
Still with error. Doesn't give any items or xp etc etc but the join message works.


[10:44:22] [Server thread/WARN]: [FirstJoinPlus] Task #87 for FirstJoinPlus v2.3 generated an exception
java.lang.NullPointerException
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[spigot.jar:git-Spigot-bc01c3a-935349e]
	at com.chaseoes.firstjoinplus.utilities.Utilities.getFirstJoinKit(Utilities.java:76) ~[?:?]
	at com.chaseoes.firstjoinplus.FirstJoinListener$1.run(FirstJoinListener.java:35) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
[10:44:22] [Server thread/WARN]: [FirstJoinPlus] Task #98 for FirstJoinPlus v2.3 generated an exception
java.lang.NullPointerException
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[spigot.jar:git-Spigot-bc01c3a-935349e]
	at com.chaseoes.firstjoinplus.utilities.Utilities.getFirstJoinKit(Utilities.java:76) ~[?:?]
	at com.chaseoes.firstjoinplus.FirstJoinListener$1.run(FirstJoinListener.java:35) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
[10:44:22] [Server thread/WARN]: [FirstJoinPlus] Task #109 for FirstJoinPlus v2.3 generated an exception
java.lang.NullPointerException
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[spigot.jar:git-Spigot-bc01c3a-935349e]
	at com.chaseoes.firstjoinplus.utilities.Utilities.getFirstJoinKit(Utilities.java:76) ~[?:?]
	at com.chaseoes.firstjoinplus.FirstJoinListener$1.run(FirstJoinListener.java:35) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
[10:44:22] [Server thread/WARN]: Brexain moved too quickly! -0.7650122225942084,-5.750812921255317,-38.819785352501526
[10:44:22] [Server thread/INFO]: [Magic] Essentials found, hooked up custom item handler
[10:44:23] [Server thread/WARN]: Chasen moved too quickly! 0.8698154488314458,-2.3753565589477716,-121.06240154154585
[10:44:23] [Server thread/INFO]: [Magic] Loading lost wand data
[10:44:23] [Server thread/INFO]: [Magic] Loaded 0 lost wands
[10:44:23] [Server thread/INFO]: [Magic] Loading automata data

**Comment by chaseoes** [comment]
It looks like you're using bad item names in your configuration for the first join kit. Pastebin your configuration?

**Comment by ManBeastPig** [comment]
No problem but I have it on 2 servers with 2 configs and the same issue.
This server..
http://pastebin.com/ghvxxxJH

My other server....
http://pastebin.com/6qNda1Ee
This one gives the kit to players but not the xp

**Comment by chaseoes** [comment]
Can you try running `/fjp setspawn` to set the spawn location again and see if that fixes it?

**Comment by chaseoes** [comment]
Okay, figured out your issues.

1. It looks like the spawn point you have is invalid somehow -- possibly the world it's set to is invalid or deleted? Set the first join spawn again by running `/fjp setspawn` just to make sure it's correct on both servers.
2. You're using a wrong item name in the configuration for the kit. You have `planks:64`. If you're looking for wooden planks, you should be using `wood:64`. There's a link on the main page of the BukkitDev project to a full list of item names, under the configuration, under "Configuration Tips".

**Comment by chaseoes** [comment]
Resolved in e93e28708d4dff6c55f4f748df1de34a98d4524c to show a friendlier error message when using the wrong material names.

**Comment by ManBeastPig** [comment]
1. The fjp setspawn was correct but i moved it and reset it just to test with no difference.
I have a feeling it might have been set on a slab however, so half block height.

2. I changed it to wood and it works fine now, thanks. It was my old config so it did work until this release. Assume bukkit api names changed maybe.

**Comment by ManBeastPig** [comment]
I deleted the config and generated a default one. I changed it to firstjoin each time true.
Touched nothing else and still error...


[08:52:05] [Server thread/INFO]: MrSulu issued server command: /fjp reload
[08:52:07] [Server thread/INFO]: MrSulu lost connection: Disconnected
[08:52:07] [Server thread/INFO]: MrSulu left the game.
[08:52:13] [User Authenticator #40/INFO]: UUID of player MrSulu is 080115a9-8ed3-4269-b049-f9974d497ae2
[08:52:14] [Server thread/INFO]: MrSulu[/77.97.153.251:47794] logged in with entity id 429443 at ([FiresOfTitan]-620.5, 89.0, 69.5)
[08:52:14] [Craft Scheduler Thread - 810/INFO]: [GAListener] Player: MrSulu has 71 votes
[08:52:14] [Server thread/WARN]: [FirstJoinPlus] Task #2919 for FirstJoinPlus v2.3 generated an exception
java.lang.NullPointerException
	at com.chaseoes.firstjoinplus.FirstJoinListener$1.run(FirstJoinListener.java:59) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-bc01c3a-935349e]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-bc01c3a-935349e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by chaseoes** [comment]
Dang, looks like the default configuration still has a wrong sound name as these were also changed in 1.9. Find this line in it:

    sound: level_up

And change it to this:

      sound-name: entity_player_levelup

**Comment by ManBeastPig** [comment]
See i'm not mad :D

**Comment by chaseoes** [comment]
Addressed it in cb6f0c42d11766852ed2bcb80544674ca7f82b41.

**Comment by ManBeastPig** [comment]
Fixed
