### ISSUE TITLE
Metrics using deprecated getOnlinePlayers in FirstJoinPlus v2.4

### ISSUE THREAD

**Issue by sgrayme** [chaseoes/FirstJoinPlus#46]
I believe this was missed with the 1.9 compatibility updates.

```[15:50:34 WARN]: Exception in thread "Craft Scheduler Thread - 2"
[15:50:34 WARN]: org.apache.commons.lang.UnhandledException: Plugin FirstJoinPlus v2.4 generated an exception while executing
 task 37
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.mcstats.Metrics.postPlugin(Metrics.java:357)
        at org.mcstats.Metrics.access$4(Metrics.java:350)
        at org.mcstats.Metrics$1.run(Metrics.java:245)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 4 more```

Using Bukkit/Spigot/Paper 1.9.4

**Comment by chaseoes** [comment]
This should not be the case. I updated it to use Metrics R8, which is updated to 1.9: https://github.com/chaseoes/FirstJoinPlus/blob/master/pom.xml#L138

**Comment by sgrayme** [comment]
I'll look some more into the error. This is the file I'm using: http://dev.bukkit.org/bukkit-plugins/firstjoinplus/files/28-first-join-plus-v2-4/

**Comment by chaseoes** [comment]
Is this still an issue?
