### ISSUE TITLE
FirstJoinPlus load errors

### ISSUE THREAD

**Issue by DataPools** [chaseoes/FirstJoinPlus#51]
I'm on Spigot 1.8.4
I used both FirstJoinPlus 2.2 and 2.4 and get the same error

`[20:42:21]
 [Server thread/ERROR]: Could not load 'plugins/FirstJoinPlus.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:77) ~[server.jar:git-PaperSpigot-5136053-db5fd9c]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[server.jar:git-PaperSpigot-5136053-db5fd9c]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [server.jar:git-PaperSpigot-5136053-db5fd9c]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [server.jar:git-PaperSpigot-5136053-db5fd9c]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [server.jar:git-PaperSpigot-5136053-db5fd9c]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [server.jar:git-PaperSpigot-5136053-db5fd9c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[server.jar:git-PaperSpigot-5136053-db5fd9c]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:75) ~[server.jar:git-PaperSpigot-5136053-db5fd9c]
	... 6 more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_51]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_51]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_51]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[server.jar:git-PaperSpigot-5136053-db5fd9c]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:75) ~[server.jar:git-PaperSpigot-5136053-db5fd9c]
	... 6 more`

**Comment by chaseoes** [comment]
Have you tried re-downloading FirstJoinPlus? It looks like yours could have been corrupted somehow.

**Comment by DataPools** [comment]
Yeah, both were from BukkitDev.

**Comment by DataPools** [comment]
It seems to get corrupted every restart. I can load it in after one restart or with plugman, but the next restart it corrupts.

**Comment by DataPools** [comment]
Ok, so I narrowed it down. The plugin corrupts itself every reload. I tested this on 2.2, 2.3, and 2.4 and on 2 different servers. Both are running Spigot 1.8.4.

**Comment by DataPools** [comment]
Fixed by updating to 2.4.1

**Comment by chaseoes** [comment]
You probably had the auto updater enabled and something weird was happening when it was updating each reload?
